/**
 * Application types and form field definitions for Apply (permits/visas).
 * Icons are Lucide component names (e.g. 'Briefcase'); map in UI with lucide-react.
 */
export const APPLICATION_TYPES = {
  work_permit: {
    id: 'work_permit',
    name: 'Work Permit',
    icon: 'Briefcase',
    description: 'Apply for or extend a work permit in Canada',
    url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/permit.html',
    applyUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/application/account.html',
    processingTime: '2-16 weeks',
    fee: '$155',
  },
  study_permit: {
    id: 'study_permit',
    name: 'Study Permit',
    icon: 'GraduationCap',
    description: 'Apply for or extend a study permit in Canada',
    url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html',
    applyUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/application/account.html',
    processingTime: '4-16 weeks',
    fee: '$150',
  },
  visitor_visa: {
    id: 'visitor_visa',
    name: 'Visitor Visa',
    icon: 'Plane',
    description: 'Apply for a visitor visa (TRV) to Canada',
    url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada.html',
    applyUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/application/account.html',
    processingTime: '2-8 weeks',
    fee: '$100',
  },
  pr_card: {
    id: 'pr_card',
    name: 'PR Card Renewal',
    icon: 'Heart',
    description: 'Renew your Permanent Resident card',
    url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/new-immigrants/pr-card.html',
    applyUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/application/account.html',
    processingTime: '6-12 weeks',
    fee: '$50',
  },
};

export const APPLICATION_FIELDS = {
  work_permit: [
    { id: 'given_name', label: 'Given Name(s)', type: 'text', required: true },
    { id: 'family_name', label: 'Family Name', type: 'text', required: true },
    { id: 'dob', label: 'Date of Birth', type: 'date', required: true },
    { id: 'country_birth', label: 'Country of Birth', type: 'text', required: true },
    { id: 'country_citizenship', label: 'Country of Citizenship', type: 'text', required: true },
    { id: 'passport_number', label: 'Passport Number', type: 'text', required: true },
    { id: 'passport_expiry', label: 'Passport Expiry Date', type: 'date', required: true },
    { id: 'email', label: 'Email Address', type: 'email', required: true },
    { id: 'phone', label: 'Phone Number', type: 'tel', required: true },
    { id: 'address_canada', label: 'Address in Canada', type: 'address', required: false },
    { id: 'employer_name', label: 'Employer Name', type: 'text', required: true },
    { id: 'employer_address', label: 'Employer Address', type: 'address', required: true },
    { id: 'job_title', label: 'Job Title', type: 'text', required: true },
    { id: 'lmia_number', label: 'LMIA Number (if applicable)', type: 'text', required: false },
    { id: 'start_date', label: 'Intended Start Date', type: 'date', required: true },
    { id: 'end_date', label: 'Intended End Date', type: 'date', required: true },
  ],
  study_permit: [
    { id: 'given_name', label: 'Given Name(s)', type: 'text', required: true },
    { id: 'family_name', label: 'Family Name', type: 'text', required: true },
    { id: 'dob', label: 'Date of Birth', type: 'date', required: true },
    { id: 'country_birth', label: 'Country of Birth', type: 'text', required: true },
    { id: 'country_citizenship', label: 'Country of Citizenship', type: 'text', required: true },
    { id: 'passport_number', label: 'Passport Number', type: 'text', required: true },
    { id: 'passport_expiry', label: 'Passport Expiry Date', type: 'date', required: true },
    { id: 'email', label: 'Email Address', type: 'email', required: true },
    { id: 'phone', label: 'Phone Number', type: 'tel', required: true },
    { id: 'school_name', label: 'School/Institution Name', type: 'text', required: true },
    { id: 'dli_number', label: 'DLI Number', type: 'text', required: true },
    { id: 'program_name', label: 'Program Name', type: 'text', required: true },
    { id: 'program_start', label: 'Program Start Date', type: 'date', required: true },
    { id: 'program_end', label: 'Program End Date', type: 'date', required: true },
  ],
  visitor_visa: [
    { id: 'given_name', label: 'Given Name(s)', type: 'text', required: true },
    { id: 'family_name', label: 'Family Name', type: 'text', required: true },
    { id: 'dob', label: 'Date of Birth', type: 'date', required: true },
    { id: 'country_citizenship', label: 'Country of Citizenship', type: 'text', required: true },
    { id: 'passport_number', label: 'Passport Number', type: 'text', required: true },
    { id: 'passport_expiry', label: 'Passport Expiry Date', type: 'date', required: true },
    { id: 'email', label: 'Email Address', type: 'email', required: true },
    { id: 'purpose', label: 'Purpose of Visit', type: 'text', required: true },
    { id: 'travel_dates', label: 'Planned Travel Dates', type: 'text', required: true },
  ],
  pr_card: [
    { id: 'given_name', label: 'Given Name(s)', type: 'text', required: true },
    { id: 'family_name', label: 'Family Name', type: 'text', required: true },
    { id: 'dob', label: 'Date of Birth', type: 'date', required: true },
    { id: 'pr_number', label: 'PR Number (A#)', type: 'text', required: true },
    { id: 'current_address', label: 'Current Address in Canada', type: 'address', required: true },
    { id: 'email', label: 'Email Address', type: 'email', required: true },
    { id: 'phone', label: 'Phone Number', type: 'tel', required: true },
  ],
};
