/**
 * Quiz options and category mappings for WelcomeGuide onboarding.
 */

export const ROLES = [
  { id: 'student', label: 'Student', icon: '📚', desc: 'Exams, tuition, enrollment' },
  { id: 'employee', label: 'Employee', icon: '💼', desc: 'Work schedule, pay, contracts' },
  { id: 'business_owner', label: 'Business Owner', icon: '🏢', desc: 'Licenses, taxes, employees' },
  { id: 'freelancer', label: 'Freelancer / Self-Employed', icon: '🎯', desc: 'Invoices, taxes, clients' },
  { id: 'newcomer', label: 'Newcomer / Immigrant', icon: '✈️', desc: 'Visas, permits, settlement' },
  { id: 'parent', label: 'Parent / Family', icon: '👨‍👩‍👧', desc: 'Kids, health, school, housing' },
  { id: 'homeowner', label: 'Homeowner', icon: '🏠', desc: 'Mortgage, property tax, maintenance' },
  { id: 'renter', label: 'Renter', icon: '🏡', desc: 'Lease, bills, tenant insurance' },
  { id: 'driver', label: 'Driver', icon: '🚗', desc: 'License, registration, tickets' },
  { id: 'landlord', label: 'Landlord / Property Owner', icon: '🔑', desc: 'Tenants, inspections, permits' },
  { id: 'retiree', label: 'Retiree / Senior', icon: '🌅', desc: 'Pensions, benefits, health' },
  { id: 'caregiver', label: 'Caregiver', icon: '🤝', desc: 'Appointments, medications, paperwork' },
  { id: 'tradesperson', label: 'Tradesperson / Contractor', icon: '🔧', desc: 'Certifications, permits, safety' },
  { id: 'athlete_coach', label: 'Athlete / Coach', icon: '🏆', desc: 'Registrations, certifications, schedules' },
  { id: 'healthcare', label: 'Healthcare Worker', icon: '⚕️', desc: 'Licenses, training, certifications' },
  { id: 'fitness', label: 'Fitness / Active', icon: '💪', desc: 'Workouts, goals, gym, running' },
  { id: 'volunteer', label: 'Volunteer', icon: '🤲', desc: 'Commitments, training, background checks' },
  { id: 'pet_owner', label: 'Pet Owner', icon: '🐾', desc: 'Vet, vaccinations, licenses, insurance' },
  { id: 'investor', label: 'Investor', icon: '📈', desc: 'Portfolio, tax docs, statements' },
  { id: 'other', label: 'Other', icon: '🔹', desc: "Something else that describes you" },
];

export const FOCUS_AREAS = [
  { id: 'deadlines', label: 'Missing deadlines', icon: '⏰' },
  { id: 'tickets', label: 'Traffic tickets, tolls & fines', icon: '🅿️' },
  { id: 'taxes', label: 'Tax filing dates', icon: '💰' },
  { id: 'renewals', label: 'Document renewals (license, passport, etc.)', icon: '📄' },
  { id: 'bills', label: 'Bills & payments', icon: '💸' },
  { id: 'appointments', label: 'Appointments & bookings', icon: '📅' },
  { id: 'visa_immigration', label: 'Visa & immigration paperwork', icon: '✈️' },
  { id: 'school', label: 'School & exam deadlines', icon: '📚' },
  { id: 'vehicle', label: 'Vehicle registration & maintenance', icon: '🚗' },
  { id: 'compliance', label: 'Business compliance & filings', icon: '📋' },
  { id: 'employee_docs', label: 'Employee paperwork & onboarding', icon: '👥' },
  { id: 'insurance', label: 'Insurance renewals', icon: '🛡️' },
  { id: 'lease_rent', label: 'Lease & rent deadlines', icon: '🏡' },
  { id: 'government', label: 'Government forms & applications', icon: '🏛️' },
  { id: 'health', label: 'Health appointments & prescriptions', icon: '❤️' },
  { id: 'kids', label: "Kids' school & activities", icon: '👧' },
  { id: 'contracts', label: 'Contracts & agreements', icon: '📝' },
  { id: 'certifications', label: 'Professional certifications & training', icon: '🎓' },
  { id: 'estate', label: 'Estate planning & wills', icon: '📜' },
  { id: 'equipment', label: 'Equipment & asset tracking', icon: '📦' },
  { id: 'fitness', label: 'Workouts & fitness goals', icon: '💪' },
  { id: 'subscriptions', label: 'Subscriptions & memberships', icon: '🔄' },
  { id: 'pet_care', label: 'Pet care & vet appointments', icon: '🐕' },
  { id: 'moving', label: 'Moving & change of address', icon: '🚚' },
  { id: 'other', label: 'Other', icon: '🔹' },
];

export const ORG_TYPES = [
  { id: 'small_business', label: 'Small Business', icon: '🏪', desc: 'Retail, restaurant, service' },
  { id: 'tech_company', label: 'Tech / Equipment Company', icon: '⚙️', desc: 'Hardware, IoT, security systems' },
  { id: 'construction', label: 'Construction / Trades', icon: '🏗️', desc: 'Contractors, builders, trades' },
  { id: 'professional_services', label: 'Professional Services', icon: '💼', desc: 'Law, accounting, consulting' },
  { id: 'healthcare_org', label: 'Healthcare / Clinic', icon: '🏥', desc: 'Clinic, dental, pharmacy' },
  { id: 'school', label: 'School / Educational', icon: '🎓', desc: 'K-12, college, training center' },
  { id: 'nonprofit', label: 'Nonprofit / Charity', icon: '💚', desc: 'Foundation, community org' },
  { id: 'sports_recreation', label: 'Sports / Recreation', icon: '🏆', desc: 'League, gym, club' },
  { id: 'property_management', label: 'Property Management', icon: '🏢', desc: 'Buildings, rentals, facilities' },
  { id: 'transportation', label: 'Transportation / Logistics', icon: '🚛', desc: 'Fleet, delivery, shipping' },
  { id: 'manufacturing', label: 'Manufacturing', icon: '🏭', desc: 'Production, assembly, warehouse' },
  { id: 'other', label: 'Other', icon: '🔹', desc: 'Something else' },
];

export const ORG_FOCUS_AREAS = [
  { id: 'employee_compliance', label: 'Employee docs & compliance', icon: '👥' },
  { id: 'licenses_permits', label: 'Licenses & permits expiring', icon: '📋' },
  { id: 'tax_filings', label: 'Tax filings & deadlines', icon: '💰' },
  { id: 'insurance_coverage', label: 'Insurance renewals', icon: '🛡️' },
  { id: 'asset_maintenance', label: 'Equipment maintenance & warranties', icon: '🔧' },
  { id: 'vendor_contracts', label: 'Vendor contracts & renewals', icon: '📝' },
  { id: 'safety_inspections', label: 'Safety inspections & audits', icon: '🔍' },
  { id: 'certifications_training', label: 'Staff certifications & training', icon: '🎓' },
  { id: 'regulatory_reporting', label: 'Regulatory reporting', icon: '🏛️' },
  { id: 'lease_property', label: 'Lease & property deadlines', icon: '🏢' },
  { id: 'fleet_vehicles', label: 'Fleet & vehicle compliance', icon: '🚗' },
  { id: 'accreditation', label: 'Accreditation & audits', icon: '✅' },
  { id: 'financial_obligations', label: 'Loans, debts & obligations', icon: '💸' },
  { id: 'data_privacy', label: 'Data & privacy compliance', icon: '🔒' },
  { id: 'other', label: 'Other', icon: '🔹' },
];

export const ROLE_CATEGORIES = {
  student: ['education', 'trust', 'retirement_estate', 'health', 'immigration'],
  employee: ['work_schedule', 'trust', 'retirement_estate', 'health', 'driving'],
  business_owner: ['trust', 'retirement_estate', 'employees', 'business_tax', 'business_license', 'business_insurance', 'assets', 'liabilities'],
  freelancer: ['trust', 'retirement_estate', 'business_tax', 'professional', 'business_insurance'],
  newcomer: ['immigration', 'trust', 'health', 'driving', 'housing'],
  parent: ['trust', 'retirement_estate', 'health', 'education', 'housing', 'driving'],
  homeowner: ['trust', 'retirement_estate', 'housing', 'property', 'tax'],
  renter: ['trust', 'retirement_estate', 'housing'],
  driver: ['driving', 'parking', 'trust'],
  landlord: ['trust', 'retirement_estate', 'property', 'business_tax', 'business_insurance', 'housing'],
  retiree: ['retirement_estate', 'trust', 'health', 'tax'],
  caregiver: ['trust', 'retirement_estate', 'health', 'housing'],
  tradesperson: ['trust', 'professional', 'business_license', 'business_insurance', 'business_tax'],
  athlete_coach: ['inst_sports', 'health', 'trust'],
  healthcare: ['professional', 'health', 'inst_staff', 'trust'],
  fitness: ['fitness', 'health', 'trust'],
  volunteer: ['important_dates', 'health', 'trust'],
  pet_owner: ['pet_care', 'health', 'trust'],
  investor: ['trust', 'retirement_estate', 'tax'],
  other: ['trust', 'retirement_estate', 'other'],
};

export const FOCUS_AREA_CATEGORIES = {
  deadlines: ['education', 'work_schedule', 'immigration'],
  tickets: ['parking', 'driving'],
  taxes: ['tax', 'business_tax'],
  renewals: ['driving', 'immigration', 'health', 'professional', 'business_license'],
  bills: ['housing', 'office'],
  appointments: ['health', 'education', 'work_schedule'],
  visa_immigration: ['immigration'],
  school: ['education'],
  vehicle: ['driving', 'parking'],
  compliance: ['business_license', 'inst_regulatory', 'professional'],
  employee_docs: ['employees', 'inst_staff'],
  insurance: ['business_insurance', 'inst_legal', 'health'],
  lease_rent: ['housing'],
  government: ['immigration', 'business_license', 'inst_regulatory'],
  health: ['health'],
  kids: ['education', 'health'],
  contracts: ['employees', 'office', 'housing'],
  certifications: ['professional', 'inst_staff'],
  estate: ['retirement_estate', 'trust'],
  equipment: ['assets'],
  fitness: ['fitness', 'health'],
  subscriptions: ['subscriptions'],
  pet_care: ['pet_care', 'health'],
  moving: ['moving', 'housing'],
  other: ['other'],
};

export const ORG_TYPE_CATEGORIES = {
  small_business: ['business_license', 'business_tax', 'business_insurance', 'employees'],
  tech_company: ['assets', 'business_license', 'business_insurance', 'employees', 'inst_safety'],
  construction: ['business_license', 'inst_safety', 'employees', 'assets', 'professional'],
  professional_services: ['professional', 'business_tax', 'business_insurance', 'employees'],
  healthcare_org: ['inst_regulatory', 'inst_staff', 'inst_safety', 'professional', 'business_insurance'],
  school: ['inst_regulatory', 'inst_staff', 'inst_programs', 'inst_safety', 'inst_finance'],
  nonprofit: ['inst_regulatory', 'inst_finance', 'inst_legal', 'inst_staff'],
  sports_recreation: ['inst_sports', 'inst_safety', 'inst_staff', 'business_insurance'],
  property_management: ['property', 'housing', 'business_insurance', 'inst_safety'],
  transportation: ['assets', 'driving', 'business_insurance', 'employees', 'business_license'],
  manufacturing: ['assets', 'inst_safety', 'employees', 'business_license', 'inst_regulatory'],
  other: ['business_license', 'business_tax', 'employees', 'business_insurance'],
};

export const LIFE_MOMENTS = [
  { id: 'moving', label: "I'm moving", icon: '🚚', desc: 'Change of address, utilities, mail' },
  { id: 'expecting_baby', label: 'Expecting a baby', icon: '👶', desc: 'Health, benefits, daycare' },
  { id: 'new_job', label: 'Starting a new job', icon: '💼', desc: 'Tax forms, benefits, contracts' },
  { id: 'getting_married', label: 'Getting married', icon: '💍', desc: 'Name change, benefits, estate' },
  { id: 'buying_home', label: 'Buying a home', icon: '🏠', desc: 'Mortgage, insurance, property tax' },
  { id: 'retiring', label: 'Retiring soon', icon: '🌅', desc: 'Pensions, benefits, estate planning' },
  { id: 'starting_business', label: 'Starting a business', icon: '🏪', desc: 'Licenses, taxes, insurance' },
  { id: 'getting_fit', label: 'Getting fit / Working out', icon: '💪', desc: 'Gym, running, goals, habits' },
  { id: 'other', label: "Something else", icon: '🔹', desc: "Tell the AI what you're working on" },
  { id: 'none', label: "Nothing major right now", icon: '✨', desc: 'Skip this' },
];

export const LIFE_MOMENT_CATEGORIES = {
  moving: ['moving', 'housing', 'government_benefits'],
  expecting_baby: ['kids_family', 'health', 'government_benefits'],
  new_job: ['work_schedule', 'tax', 'health', 'employee_benefits'],
  getting_married: ['important_dates', 'retirement_estate', 'trust'],
  buying_home: ['housing', 'property', 'personal_insurance', 'tax'],
  retiring: ['retirement_estate', 'health', 'trust', 'government_benefits'],
  starting_business: ['business_license', 'business_tax', 'business_insurance'],
  getting_fit: ['fitness', 'health'],
  other: ['important_dates', 'health', 'education', 'other'],
  none: [],
};

export const ORG_FOCUS_AREA_CATEGORIES = {
  employee_compliance: ['employees', 'inst_staff'],
  licenses_permits: ['business_license', 'inst_regulatory'],
  tax_filings: ['business_tax'],
  insurance_coverage: ['business_insurance', 'inst_legal'],
  asset_maintenance: ['assets'],
  vendor_contracts: ['office', 'liabilities'],
  safety_inspections: ['inst_safety'],
  certifications_training: ['professional', 'inst_staff'],
  regulatory_reporting: ['inst_regulatory', 'inst_finance'],
  lease_property: ['property', 'housing', 'office'],
  fleet_vehicles: ['assets', 'driving'],
  accreditation: ['inst_regulatory'],
  financial_obligations: ['liabilities', 'inst_finance'],
  data_privacy: ['inst_regulatory'],
  other: ['other'],
};
